---

- name: Enable PostgreSQL from postgres
  yum:
    name: "{{ pg_repo_rpm_url }}"
    state: present

- name: install required yum packages
  yum: name={{ item }} state=installed
  with_items:
    - "{{ pg_package_name }}"
